# Generated by Django 5.1.4 on 2025-01-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vinyl',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='stock',
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinyl_store.artist'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinyl_store.genre'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
